[package]
name = "rust-mandelbrot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixel-canvas = "0.2.3"
confy = "0.3.1"
serde = { version = "1.0", features = ["derive"] }